[pytest]
filterwarnings =
    ignore::DeprecationWarning:pytest_asyncio.plugin
    ignore:.*'asyncio.iscoroutinefunction'.*:DeprecationWarning
    ignore:.*'asyncio.get_event_loop_policy'.*:DeprecationWarning
testpaths = tests
